markdown:       kramdown
kramdown:
  auto_ids:     true
  input: Kramdown
encoding:       UTF-8
exclude:
  - vendor
  - .git/
  - package.json
  - package-lock.json
  - node_modules

sass:
  sass_dir: ./
  style: compressed

theme: jekyll-theme-primer

plugins:
  - jekyll-seo-tag

twitter:
  username: zairah___

author:
  name: Zairah Mustahsan
